In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
import math

In [2]:
name = '1'

train = np.loadtxt('data/data'+name+'_train.csv')
X = train[:,0:2]
Y = train[:,2:3]

validate = np.loadtxt('data/data'+name+'_validate.csv')
Xval = validate[:,0:2]
Yval = validate[:,2:3]

In [3]:
class GD(object):
    
    def __init__(self, x0, objective,
                 gradient,
                 step_size=1e-1):
        self.x0 = x0
        self.objective = objective
        self.gradient = gradient
        self.step_size = step_size
        
    def compute_gradient(self, x, idx=None, eps=1e-6):
        if self.gradient != None:
            return self.gradient(x)
    
    def step(self, stochastic=False, gtol=1e-1):
        log = []
        while True:
            grad = self.compute_gradient(self.x0)
            log.append((self.x0, grad))
            if np.linalg.norm(grad) < gtol:
                break
            self.x0 = self.x0 - self.step_size * grad
            print self.x0, grad, np.linalg.norm(grad)
        return log

In [4]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

In [17]:
def Objective(X, Y, L):
    def obj(W):
        return L*W.dot(W)-sum([y*math.log(sigmoid(W.dot(x))) + (1-y)*math.log(1-sigmoid(W.dot(x))) for x,y in zip(X, Y)])
    return obj

def Gradient(X, Y, L):
    def grad(W):
        reg = np.append(np.array([0.0]), 2*L*W[1:])
        return reg + sum([(sigmoid(W[0]+W[1:].dot(x))-y)*np.append(np.array([1.0]), x) for x,y in zip(X, Y)])
    return grad

In [63]:
L = 0.0
objective = Objective(X,Y,L)
gradient = Gradient(X,Y,L)

In [64]:
w0 = np.array([0.0, 0.0, 0.0])

In [69]:
optimizer = GD(w0, objective, gradient, 1e2)

In [70]:
log = optimizer.step()

[-19800.            109.02189396  78729.21202316] [ 198.           -1.09021894 -787.29212023] 811.809134684
[ -39300.            -332.38329484  118514.32451099] [ 195.            4.41405189 -397.85112488] 443.091414294
[ -58600.            -712.98961641  158350.99726089] [ 193.            3.80606322 -398.3667275 ] 442.673170291
[ -77700.           -1039.3594351   198258.29953982] [ 191.            3.26369819 -399.07302279] 442.437486255
[ -96800.           -1365.72925379  238165.60181875] [ 191.            3.26369819 -399.07302279] 442.437486255
[-115900.           -1692.09907247  278072.90409768] [ 191.            3.26369819 -399.07302279] 442.437486255
[-135000.           -2018.46889116  317980.20637661] [ 191.            3.26369819 -399.07302279] 442.437486255
[-154000.           -2128.81061207  357930.82910259] [ 190.            1.10341721 -399.50622726] 442.387209522
[-172900.           -2033.15557029  397925.53065681] [ 189.           -0.95655042 -399.94701554] 442.356790645
[-19

/home/shankha/.local/lib/python2.7/site-packages/ipykernel/__main__.py:2: RuntimeWarning: overflow encountered in exp
  from ipykernel import kernelapp as app


[-305200.           -1363.57027779  677888.44153635] [ 189.           -0.95655042 -399.94701554] 442.356790645
[-324100.           -1267.91523601  717883.14309057] [ 189.           -0.95655042 -399.94701554] 442.356790645
[-343000.           -1172.26019422  757877.84464479] [ 189.           -0.95655042 -399.94701554] 442.356790645
[-361900.           -1076.60515244  797872.54619902] [ 189.           -0.95655042 -399.94701554] 442.356790645
[-380800.            -980.95011065  837867.24775324] [ 189.           -0.95655042 -399.94701554] 442.356790645
[-399700.            -885.29506887  877861.94930746] [ 189.           -0.95655042 -399.94701554] 442.356790645
[ -4.18600000e+05  -7.89640027e+02   9.17856651e+05] [ 189.           -0.95655042 -399.94701554] 442.356790645
[ -4.37500000e+05  -6.93984985e+02   9.57851352e+05] [ 189.           -0.95655042 -399.94701554] 442.356790645
[ -4.56400000e+05  -5.98329944e+02   9.97846054e+05] [ 189.           -0.95655042 -399.94701554] 442.356790645
[

KeyboardInterrupt: 

In [11]:
log[-1]

(array([-1446.13327751,     2.27238568,   384.88503927]),
 array([ 0.09904424,  0.00680996, -0.00840854]))

In [31]:
[W[0]+W[1:].dot(x) for x, y in zip(X,Y)]

NameError: name 'W' is not defined